language: node_js
node_js:
  - "8"
env:
  - IMAGE_NAME=${DOCKER_HUB_USERNAME}/jira-pretty-board:latest
script:
  - npm run lint
  - npm run build
  - docker build -t $IMAGE_NAME .
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
  - docker push $IMAGE_NAME
